---
- hosts: all
  become: yes
  tasks:
    - name: download mattermost
      get_url: 
         url: https://releases.mattermost.com/5.17.1/mattermost-5.17.1-linux-amd64.tar.gz
         dest: /home/ubuntu
         validate_certs: false
    - name: check file exists
      stat: 
         path: /home/ubunutu/mattermost-5.17.1-linux-amd64.tar.gz
      register: stat_result
    - name: print result
      debug: 
        msg: "{{stat_result.stat.exists == True}}"
    - name: untaring mattermost file
      unarchive: 
         src: /home/ubuntu/mattermost-5.17.1-linux-amd64.tar.gz
         dest: /home/ubuntu/
         remote_src: yes
      args:
         creates: /home/ubuntu/mattermost
    
    - name: create directory
      file: 
         path: /opt/mattermost
         state: directory

    - name: move now
      command: mv /home/ubuntu/mattermost /opt
      ignore_errors: yes

    - name: create directory
      file: 
        path: /opt/mattermost/data
        state: directory
    
    
    
    # - name: move mattermost to /opt
    #   command: mv /home/ubuntu/mattermost /opt
    #   ignore_errors: yes
    
   
    - name: create group mattermost
      group:
        name: mattermost
        state: present


    - name: adding user
      user: 
        name: mattermost
        group: mattermost
        system: yes


   # - name: adding user 
    #  command: 'sudo useradd --system --user-group mattermost'
     # ignore_errors: yes

    - name: changing ownership and mode
      file:
         path: /opt/mattermost
         owner: mattermost
         group: mattermost
         mode: 0775
         recurse: yes

